name: Windows CI - SaxonHECSharp

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Setup Saxon Libraries
      shell: pwsh
      run: |
        $downloadUrl = "https://downloads.saxonica.com/SaxonC/EE/12/SaxonCEE-windows-x86_64-12-8-0.zip"
        $targetDir = "SaxonHECSharp/runtimes"
        $nativeDir = Join-Path $targetDir "win-x64/native"
        $tempDir = "saxon-temp"
        
        # Create directories
        New-Item -ItemType Directory -Force -Path $nativeDir | Out-Null
        New-Item -ItemType Directory -Force -Path $tempDir | Out-Null
        
        Write-Host "Downloading Saxon from $downloadUrl"
        # Download and extract to temp directory first
        $zipPath = "saxon-temp.zip"
        Invoke-WebRequest -Uri $downloadUrl -OutFile $zipPath
        Expand-Archive -Path $zipPath -DestinationPath $tempDir -Force
        Remove-Item $zipPath
        
        # Move files to runtimes directory
        Write-Host "Looking for Saxon libraries in extracted contents..."
        # Find and copy library files recursively
        $binDirs = Get-ChildItem -Path $tempDir -Recurse -Directory | Where-Object { $_.Name -eq "bin" }
        foreach ($binDir in $binDirs) {
            Get-ChildItem -Path $binDir.FullName -Recurse -File | Copy-Item -Destination $nativeDir -Force
        }
        
        # Clean up extracted files
        Remove-Item -Path $tempDir -Recurse -Force
        
        # Verify setup
        $libFiles = Get-ChildItem $nativeDir
        if ($libFiles.Count -gt 0) {
            Write-Host "Saxon libraries successfully set up in $nativeDir"
            $libFiles | ForEach-Object { Write-Host "Found: $($_.Name)" }
        } else {
            Write-Error "No library files were found and copied"
            exit 1
        }

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Solution
      run: dotnet build SaxonHECSharp.sln --configuration Release /p:DefineConstants=WINDOWS

    - name: Build Example Project
      shell: pwsh
      id: build-example
      run: |
        # Verify Saxon library exists and is accessible
        $nativeLibPath = "SaxonHECSharp.Example/bin/Release/net9.0/runtimes/win-x64/native"
        
        Write-Host "Checking Saxon libraries in: ${nativeLibPath}"
        if (Test-Path -Path $nativeLibPath) {
            Get-ChildItem -Path $nativeLibPath | ForEach-Object {
                Write-Host "Found library: $($_.Name)"
                Write-Host "  Size: $($_.Length) bytes"
                Write-Host "  Last Write Time: $($_.LastWriteTime)"
            }
        } else {
            Write-Error "Native library directory not found: ${nativeLibPath}"
            exit 1
        }
        
        dotnet run --project SaxonHECSharp.Example/SaxonHECSharp.Example.csproj --configuration Release /p:DefineConstants=WINDOWS
